# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.27 Form Designer
# Date : 12/06/2026
# Time : 15:27:11

Load "stdlibcore.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new App {
		StyleFusion()
		new AplicacionView { win.show() } 
		exec()
	}
}

class AplicacionView from WindowsViewParent
	win = new MainWindow() { 
		resize(400,374)
		setWindowTitle("Aplicacion Principal")
		setstylesheet("background-color:;") 
		Label1 = new label(win) {
			move(66,59)
			resize(275,80)
			setstylesheet("color:none;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Aplicacion Principal")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
		ButtonCerrar = new pushbutton(win) {
			move(71,222)
			resize(157,44)
			setstylesheet("color:none;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Cerrar")
			setClickEvent(Method(:Cerrar))
			setBtnImage(ButtonCerrar,"")
			
		}
	}

# End of the Generated Source Code File...