# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.27 Form Designer
# Date : 11/06/2026
# Time : 22:57:23

Load "stdlibcore.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new App {
		StyleFusion()
		new loginView { win.show() } 
		exec()
	}
}

class loginView from WindowsViewParent
	win = new MainWindow() { 
		resize(538,357)
		setWindowTitle("Login")
		setstylesheet("background-color:;") 

		setWindowFlags(Qt_dialog | Qt_WindowTitleHint | Qt_WindowMinimizeButtonHint | Qt_WindowCloseButtonHint) 
		Image1 = new label(win) {
			move(-6,-2)
			resize(278,357)
			setstylesheet("color:none;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setPixMap(New qPixMap("/home/valcoellar/Dropbox/Ring/LOGIN_TEST/log.jpg"))
			
		}
		Label1 = new label(win) {
			move(304,24)
			resize(163,42)
			setstylesheet("color:none;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Usuario")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
		TextEditUser = new textedit(win) {
			move(298,74)
			resize(203,30)
			setstylesheet("color:none;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("")
			setcopyAvailableEvent("")
			setcurrentCharFormatChangedEvent("")
			setcursorPositionChangedEvent("")
			setredoAvailableEvent("")
			setselectionChangedEvent("")
			settextChangedEvent("")
			setundoAvailableEvent("")
			
		}
		Label4 = new label(win) {
			move(304,132)
			resize(163,42)
			setstylesheet("color:none;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Contraseña")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
		TextEditPass = new textedit(win) {
			move(299,184)
			resize(203,33)
			setstylesheet("color:none;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("")
			setcopyAvailableEvent("")
			setcurrentCharFormatChangedEvent("")
			setcursorPositionChangedEvent("")
			setredoAvailableEvent("")
			setselectionChangedEvent("")
			settextChangedEvent("")
			setundoAvailableEvent("")
			
		}
		ButtonLogin = new pushbutton(win) {
			move(341,268)
			resize(118,35)
			setstylesheet("color:none;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Entrar")
			setClickEvent(Method(:Entrar))
			setBtnImage(ButtonLogin,"")
			
		}
	}

# End of the Generated Source Code File...