# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.27 Form Designer
# Date : 07/06/2026
# Time : 22:18:35

Load "stdlibcore.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new App {
		StyleFusion()
		new CajaRegistradoraView { win.show() } 
		exec()
	}
}

class CajaRegistradoraView from WindowsViewParent
	win = new MainWindow() { 
		resize(593,390)
		setWindowTitle("Caja Registradora Simple")
		setstylesheet("background-color:;") 
		Label1 = new label(win) {
			move(20,22)
			resize(44,25)
			setstylesheet("color:none;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Cajero")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
		TextEditCajero = new textedit(win) {
			move(96,14)
			resize(96,33)
			setstylesheet("color:none;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("")
			setcopyAvailableEvent("")
			setcurrentCharFormatChangedEvent("")
			setcursorPositionChangedEvent("")
			setredoAvailableEvent("")
			setselectionChangedEvent("")
			settextChangedEvent("")
			setundoAvailableEvent("")
			
		}
		TextEditArticulo = new textedit(win) {
			move(279,14)
			resize(96,33)
			setstylesheet("color:none;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("")
			setcopyAvailableEvent("")
			setcurrentCharFormatChangedEvent("")
			setcursorPositionChangedEvent("")
			setredoAvailableEvent("")
			setselectionChangedEvent("")
			settextChangedEvent("")
			setundoAvailableEvent("")
			
		}
		TextEditPrecio = new textedit(win) {
			move(460,14)
			resize(96,33)
			setstylesheet("color:none;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("")
			setcopyAvailableEvent("")
			setcurrentCharFormatChangedEvent("")
			setcursorPositionChangedEvent("")
			setredoAvailableEvent("")
			setselectionChangedEvent("")
			settextChangedEvent("")
			setundoAvailableEvent("")
			
		}
		Label5 = new label(win) {
			move(219,24)
			resize(44,25)
			setstylesheet("color:none;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Articulo")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
		Label6 = new label(win) {
			move(408,23)
			resize(44,25)
			setstylesheet("color:none;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Precio")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
		TableWidget1 = new tablewidget(win) {
			move(28,94)
			resize(527,250)
			setstylesheet("color:none;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setRowCount(1)
			setColumnCount(4)
			setHorizontalHeaderItem(1, new QTableWidgetItem("Art"))
			setHorizontalHeaderItem(2, new QTableWidgetItem("PU"))
			setHorizontalHeaderItem(3, new QTableWidgetItem(""))
			setHorizontalHeaderItem(4, new QTableWidgetItem("Atendio"))
			setSelectionBehavior(QAbstractItemView_SelectRows)
			setAlternatingRowColors(False)
			setcellActivatedEvent("")
			setcellChangedEvent("")
			setcellClickedEvent("")
			setcellDoubleClickedEvent("")
			setcellEnteredEvent("")
			setcellPressedEvent("")
			setcurrentCellChangedEvent("")
			setcurrentItemChangedEvent("")
			setitemActivatedEvent("")
			setitemChangedEvent("")
			setitemClickedEvent("")
			setitemDoubleClickedEvent("")
			setitemEnteredEvent("")
			setitemPressedEvent("")
			setitemSelectionChangedEvent("")
			
		}
		Button1Agregar = new pushbutton(win) {
			move(483,54)
			resize(70,30)
			setstylesheet("color:none;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Agregar")
			setClickEvent(Method(:Agregar))
			setBtnImage(Button1Agregar,"")
			
		}
		Label4 = new label(win) {
			move(36,351)
			resize(90,26)
			setstylesheet("color:none;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Subtotal")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
		TextEditSubtotal = new textedit(win) {
			move(111,349)
			resize(94,28)
			setstylesheet("color:none;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("")
			setcopyAvailableEvent("")
			setcurrentCharFormatChangedEvent("")
			setcursorPositionChangedEvent("")
			setredoAvailableEvent("")
			setselectionChangedEvent("")
			settextChangedEvent("")
			setundoAvailableEvent("")
			
		}
		Label11 = new label(win) {
			move(215,351)
			resize(90,26)
			setstylesheet("color:none;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Impuesto")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
		TextEditImpuesto = new textedit(win) {
			move(280,349)
			resize(94,28)
			setstylesheet("color:none;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("")
			setcopyAvailableEvent("")
			setcurrentCharFormatChangedEvent("")
			setcursorPositionChangedEvent("")
			setredoAvailableEvent("")
			setselectionChangedEvent("")
			settextChangedEvent("")
			setundoAvailableEvent("")
			
		}
		Label13 = new label(win) {
			move(390,351)
			resize(90,26)
			setstylesheet("color:none;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Total")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
		TextEditTotal = new textedit(win) {
			move(428,349)
			resize(94,28)
			setstylesheet("color:none;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("")
			setcopyAvailableEvent("")
			setcurrentCharFormatChangedEvent("")
			setcursorPositionChangedEvent("")
			setredoAvailableEvent("")
			setselectionChangedEvent("")
			settextChangedEvent("")
			setundoAvailableEvent("")
			
		}
	}

# End of the Generated Source Code File...