# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.27 Form Designer
# Date : 01/06/2026
# Time : 22:25:49

Load "stdlibcore.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new App {
		StyleFusion()
		new TextFieldSaverView { win.show() } 
		exec()
	}
}

class TextFieldSaverView from WindowsViewParent
	win = new MainWindow() { 
		resize(400,374)
		setWindowTitle("Text Field Saver")
		setstylesheet("background-color:;") 
		LineEdit1 = new lineedit(win) {
			move(70,45)
			resize(233,36)
			setstylesheet("color:none;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent("")
			setselectionChangedEvent("")
			settextEditedEvent("")
			
		}
		LineEdit2 = new lineedit(win) {
			move(70,121)
			resize(233,40)
			setstylesheet("color:none;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent("")
			setselectionChangedEvent("")
			settextEditedEvent("")
			
		}
		LineEdit3 = new lineedit(win) {
			move(70,201)
			resize(233,40)
			setstylesheet("color:none;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent("")
			setselectionChangedEvent("")
			settextEditedEvent("")
			
		}
		Button1 = new pushbutton(win) {
			move(72,272)
			resize(131,38)
			setstylesheet("color:none;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Guardar")
			setClickEvent(Method(:GuardarAction))
			setBtnImage(Button1,"")
			
		}
	}

# End of the Generated Source Code File...