# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.27 Form Designer
# Date : 01/06/2026
# Time : 20:26:03

Load "stdlibcore.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new App {
		StyleFusion()
		new FormularioPrincipalView { win.show() } 
		exec()
	}
}

class FormularioPrincipalView from WindowsViewParent
	win = new MainWindow() { 
		resize(450,228)
		setWindowTitle("Trading timer V0.0.5 Ring")
		setstylesheet("background-color:;") 

		oMenuBar = new qmenubar(win) {
		}
		win.SetMenuBar(oMenuBar)
 
		TextEdit1 = new textedit(win) {
			move(39,48)
			resize(90,35)
			setstylesheet("color:none;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("DejaVu Sans,14,-1,5,75,0,0,0,0,0,Bold")
			setfont(oFont)
			oFont.delete()
			setText("00:00")
			setcopyAvailableEvent("")
			setcurrentCharFormatChangedEvent("")
			setcursorPositionChangedEvent("")
			setredoAvailableEvent("")
			setselectionChangedEvent("")
			settextChangedEvent("")
			setundoAvailableEvent("")
			
		}
		BotonCerrar = new pushbutton(win) {
			move(345,179)
			resize(90,40)
			setstylesheet("color:none;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Cerrar")
			setClickEvent(Method(:Cerrar))
			setBtnImage(BotonCerrar,"")
			
		}
		BotonAjusta5 = new pushbutton(win) {
			move(37,106)
			resize(92,31)
			setstylesheet("color:none;background-color:#33d17a;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Set")
			setClickEvent(Method(:Ajusta_Cinco))
			setBtnImage(BotonAjusta5,"")
			
		}
		Timer5 = new qtimer(win) {
			setInterval(1000)
			setTimeoutevent("")
			start()
			
		}
		TextEdit6 = new textedit(win) {
			move(169,48)
			resize(90,35)
			setstylesheet("color:none;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("DejaVu Sans,14,-1,5,75,0,0,0,0,0,Bold")
			setfont(oFont)
			oFont.delete()
			setText("00:00")
			setcopyAvailableEvent("")
			setcurrentCharFormatChangedEvent("")
			setcursorPositionChangedEvent("")
			setredoAvailableEvent("")
			setselectionChangedEvent("")
			settextChangedEvent("")
			setundoAvailableEvent("")
			
		}
		BotonAjusta7 = new pushbutton(win) {
			move(169,106)
			resize(92,35)
			setstylesheet("color:none;background-color:#33d17a;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Set")
			setClickEvent(Method(:Ajusta_Quince))
			setBtnImage(BotonAjusta7,"")
			
		}
		Label2 = new label(win) {
			move(38,14)
			resize(86,27)
			setstylesheet("color:none;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("5 Minutos")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
		Label8 = new label(win) {
			move(174,14)
			resize(86,27)
			setstylesheet("color:none;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("15 Minutos")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
		Label9 = new label(win) {
			move(310,14)
			resize(86,27)
			setstylesheet("color:none;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("1 Hora")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
		BotonAjusta10 = new pushbutton(win) {
			move(301,106)
			resize(92,35)
			setstylesheet("color:none;background-color:#33d17a;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Set")
			setClickEvent(Method(:Ajusta_Sesenta))
			setBtnImage(BotonAjusta10,"")
			
		}
		TextEdit11 = new textedit(win) {
			move(299,48)
			resize(90,35)
			setstylesheet("color:none;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("DejaVu Sans,14,-1,5,75,0,0,0,0,0,Bold")
			setfont(oFont)
			oFont.delete()
			setText("00:00")
			setcopyAvailableEvent("")
			setcurrentCharFormatChangedEvent("")
			setcursorPositionChangedEvent("")
			setredoAvailableEvent("")
			setselectionChangedEvent("")
			settextChangedEvent("")
			setundoAvailableEvent("")
			
		}
		Label4 = new label(win) {
			move(7,205)
			resize(323,23)
			setstylesheet("color:none;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Valentin Coellar S. 2026 dieccion@gruponucleon.com")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
	}

# End of the Generated Source Code File...