# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.27 Form Designer
# Date : 02/06/2026
# Time : 22:43:59

Load "stdlibcore.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new App {
		StyleFusion()
		new TextEditorView { win.show() } 
		exec()
	}
}

class TextEditorView from WindowsViewParent
	win = new MainWindow() { 
		resize(651,514)
		setWindowTitle("Text Editor")
		setstylesheet("background-color:;") 

		setWindowFlags(Qt_Window | Qt_WindowTitleHint | Qt_WindowMinimizeButtonHint | Qt_WindowCloseButtonHint) 
		Label1 = new label(win) {
			move(18,5)
			resize(130,31)
			setstylesheet("color:none;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Text Editor")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
		NombreArchivo = new lineedit(win) {
			move(17,42)
			resize(596,25)
			setstylesheet("color:none;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent("")
			setselectionChangedEvent("")
			settextEditedEvent("")
			
		}
		TextEdit1 = new textedit(win) {
			move(17,84)
			resize(600,350)
			setstylesheet("color:none;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("")
			setcopyAvailableEvent("")
			setcurrentCharFormatChangedEvent("")
			setcursorPositionChangedEvent("")
			setredoAvailableEvent("")
			setselectionChangedEvent("")
			settextChangedEvent("")
			setundoAvailableEvent("")
			
		}
		Button1 = new pushbutton(win) {
			move(24,466)
			resize(71,31)
			setstylesheet("color:none;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Cargar")
			setClickEvent(Method(:LoadFile))
			setBtnImage(Button1,"")
			
		}
		Button5 = new pushbutton(win) {
			move(113,467)
			resize(71,31)
			setstylesheet("color:none;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Guardar")
			setClickEvent(Method(:SaveFile))
			setBtnImage(Button5,"")
			
		}
	}

# End of the Generated Source Code File...