# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.27 Form Designer
# Date : 18/06/2026
# Time : 21:50:19

Load "stdlibcore.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new App {
		StyleFusion()
		new reporteView { win.show() } 
		exec()
	}
}

class reporteView from WindowsViewParent
	win = new MainWindow() { 
		resize(458,374)
		setWindowTitle("Report Test PDF")
		setstylesheet("background-color:;") 
		Button1 = new pushbutton(win) {
			move(330,327)
			resize(94,32)
			setstylesheet("color:none;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Imprimir")
			setClickEvent(Method(:imprime))
			setBtnImage(Button1,"")
			
		}
		TextEdit1 = new textedit(win) {
			move(29,27)
			resize(392,288)
			setstylesheet("color:none;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("")
			setcopyAvailableEvent("")
			setcurrentCharFormatChangedEvent("")
			setcursorPositionChangedEvent("")
			setredoAvailableEvent("")
			setselectionChangedEvent("")
			settextChangedEvent("")
			setundoAvailableEvent("")
			
		}
	}

# End of the Generated Source Code File...